odin:
  dir: /Users/noahgreen/Documents/.odin
# Node properties
node:
  note:
    extensions: 
    - md
    dirs:
    - /Users/noahgreen/Documents/Notes
  reference:
    extensions: 
    - pdf
    dirs:
    - /Users/noahgreen/Documents/References
  bibliography:
    extensions:
    - bib
    dirs:
    - /Users/noahgreen/Documents/References
  data:
    extensions:
    - root
    - csv
    dirs:
    - /Users/noahgreen/Documents/Data
  image:
    dirs:
    - /Users/noahgreen/Documents/Images
    extensions:
    - jpg
    - jpeg
    - png


