node:
  note:
    dirs:
    - /Users/noahgreen/Documents/Notes
    extensions:
    - md
  reference:
    dirs:
    - /Users/noahgreen/Documents/References
    extensions:
    - pdf
odin:
  dir: /Users/noahgreen/Documents/.odin
